// Generated by gencpp from file tourancontrol/tourancontrol.msg
// DO NOT EDIT!


#ifndef TOURANCONTROL_MESSAGE_TOURANCONTROL_H
#define TOURANCONTROL_MESSAGE_TOURANCONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tourancontrol
{
template <class ContainerAllocator>
struct tourancontrol_
{
  typedef tourancontrol_<ContainerAllocator> Type;

  tourancontrol_()
    : acceleration(0.0)
    , angular(0.0)  {
    }
  tourancontrol_(const ContainerAllocator& _alloc)
    : acceleration(0.0)
    , angular(0.0)  {
  (void)_alloc;
    }



   typedef float _acceleration_type;
  _acceleration_type acceleration;

   typedef float _angular_type;
  _angular_type angular;




  typedef boost::shared_ptr< ::tourancontrol::tourancontrol_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tourancontrol::tourancontrol_<ContainerAllocator> const> ConstPtr;

}; // struct tourancontrol_

typedef ::tourancontrol::tourancontrol_<std::allocator<void> > tourancontrol;

typedef boost::shared_ptr< ::tourancontrol::tourancontrol > tourancontrolPtr;
typedef boost::shared_ptr< ::tourancontrol::tourancontrol const> tourancontrolConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tourancontrol::tourancontrol_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tourancontrol::tourancontrol_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tourancontrol

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'tourancontrol': ['/home/xiesc/xieshichao/vehicle_control_by_keyboard/src/tourancontrol/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tourancontrol::tourancontrol_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tourancontrol::tourancontrol_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tourancontrol::tourancontrol_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tourancontrol::tourancontrol_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tourancontrol::tourancontrol_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tourancontrol::tourancontrol_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tourancontrol::tourancontrol_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3729754d76c9e6eced875888c7d60e93";
  }

  static const char* value(const ::tourancontrol::tourancontrol_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3729754d76c9e6ecULL;
  static const uint64_t static_value2 = 0xed875888c7d60e93ULL;
};

template<class ContainerAllocator>
struct DataType< ::tourancontrol::tourancontrol_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tourancontrol/tourancontrol";
  }

  static const char* value(const ::tourancontrol::tourancontrol_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tourancontrol::tourancontrol_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 acceleration\n\
float32 angular\n\
";
  }

  static const char* value(const ::tourancontrol::tourancontrol_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tourancontrol::tourancontrol_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.acceleration);
      stream.next(m.angular);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct tourancontrol_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tourancontrol::tourancontrol_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tourancontrol::tourancontrol_<ContainerAllocator>& v)
  {
    s << indent << "acceleration: ";
    Printer<float>::stream(s, indent + "  ", v.acceleration);
    s << indent << "angular: ";
    Printer<float>::stream(s, indent + "  ", v.angular);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOURANCONTROL_MESSAGE_TOURANCONTROL_H
